import $ from 'jquery'
// import 'bootstrap/dist/js/bootstrap.js'
import './js/setting.js'
import './js/index.js'
import './js/focus.js'
import './js/color.js'
import 'bootstrap/dist/css/bootstrap.min.css'
// import './css/markdownhtml.less'
// import './js/pixyll.js'
import './css/index.less'
